### ISSUE TITLE
Error: Main Exception Message: unknown error: no chrome binary at educative.io_scraper/Chrome-bin/linux/chrome/chrome

### ISSUE THREAD

**Issue by DaveIotDev** [anilabhadatta/educative.io_scraper#1]
Am i missing a step here or is the chrome binary supposed to be there?

Plaform - linux OS

**Comment by DaveIotDev** [comment]
![1 - Copy](https://user-images.githubusercontent.com/101608765/159831519-d400481d-f90b-4068-af7c-7bd723d7f1f0.JPG)

**Comment by DaveIotDev** [comment]
Thanks, getting the error below after dropping chrome bin.

**Comment by DaveIotDev** [comment]
![1 - Copy](https://user-images.githubusercontent.com/101608765/159831742-cdcc6393-4487-4f79-b56b-5d06da5be450.JPG)

**Comment by anilabhadatta** [comment]
@DaveIotDev Please confirm me 3 steps.
1. Are you running the script from educative_scraper.py?
2. If yes, then did you start chromedriver manually?
3. If yes, then restart your system, maybe the previous processes are causing issues with the port.
4. If not, then go to Chrome-driver/linux/ and open a terminal and load the chromedriver, then execute educative_scraper.py.
5. Also make sure that you create a virtualenv named "env" - mandatory step.

**Comment by anilabhadatta** [comment]
@DaveIotDev These four steps are important if you want to run from educative_scraper.py
If you want to use the releases, then you can ignore all these steps.
![image](https://user-images.githubusercontent.com/48487849/159841918-c24e3936-60f5-4b17-9f6b-acd1bbc7106c.png)

Next, you have to load the chromedriver and run educative_scraper.py.
![image](https://user-images.githubusercontent.com/48487849/159842121-30a6214e-a496-4114-b04c-390f182184fc.png)
![image](https://user-images.githubusercontent.com/48487849/159842212-8df7f1ad-e5a9-481c-9d80-91c6fe1c5641.png)

Enter 1 and provide your config details such as text file path containing URLs, save directory path, headless mode.

Login your account using 2
![image](https://user-images.githubusercontent.com/48487849/159842326-0b16d4c7-4712-4cb4-a625-11f9ca209fd2.png)

Then press enter on terminal to exit the login screen and enter 3 to start scraping

**Comment by DaveIotDev** [comment]
Are you running the script from educative_scraper.py? Yes as your ROOT path depends on it.
If yes, then did you start chromedriver manually? Yes
If yes, then restart your system, maybe the previous processes are causing issues with the port. Checked no processes
If not, then go to Chrome-driver/linux/ and open a terminal and load the chromedriver, then execute educative_scraper.py.
Also make sure that you create a virtualenv named "env" - mandatory step. Yup doing this.

So adding below files before headless argument helps.
options.add_argument('--no-sandbox')
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--remote-debugging-port=9515")

Got Rid of the DevToolsActivePort issue,but getting new error now(progress)

Main Exception Message: unknown error: Chrome failed to start: exited abnormally.
  (chrome not reachable)

Hopefully you can make those changes and it'll be useful for others.I am pausing this for now.

**Comment by anilabhadatta** [comment]
Connect with me on telegram
@ghostxriju

**Comment by anilabhadatta** [comment]
@DaveIotDev --remote-debugging-port is not needed and it shouldn't be 9515. The port 9515 is occupied by chromedriver that is used to connect to selenium webdriver via remote.webdriver. You can provide any other random port numbers as you want.
no-sandbox and dev-svm-usage arguments are already added to code.
I need to clear few things. Did you download the Chrome-bin from the latest release and have you made any changes to chromedriver?
Generally if the chromedriver and chrome version mismatches , error occurs. In the Git repo , I have included v98 chromedriver and chrome-bin so third party chromedrivers may cause issues.
If there is still error then try to give permissions to these files, using sudo chmod +x "file"
I would recommend you to restart the OS and do a git pull to clone the latest commit.
If possible contact me on telegram so I can help u instantly @ghostxriju

**Comment by anilabhadatta** [comment]
Create a new issue if problem persists.
