### ISSUE TITLE
Cant Run in Linux Server

### ISSUE THREAD

**Issue by Ex-Communicad0** [anilabhadatta/educative.io_scraper#102]
Hi, it working on Windows machine but I have a Linux server that I can run for an indefinite time so i want to use this on linux server

the Linux server I can access with both SSH & xvnc display

I can run Chrome Firefox, when i set up this everything worked, except the Chrome for testing window not displaying but it's running on the background. 

so what happening here is, that it doesn't show the display of Chrome testing browser (but normally installed Chrome working) & i can't login my credentials to start the process

can you suggest any solutions for this, i have tried searching online no proper solution found.

**Comment by anilabhadatta** [comment]
@Ex-Communicad0 Is it a x64 based linux or ARM?
Try without undetected chromedriver

**Comment by Ex-Communicad0** [comment]
> @Ex-Communicad0 Is it a x64 based linux or ARM? Try without undetected chromedriver

Hi, its amd64 version

tried, but the display is not visualizing but its working in background, is there any possibility i can import the cookie or login info by command line

if you are interested i can provide you access to check the issue by yourself, you can drop a mail so that i can send you the access details

**Comment by anilabhadatta** [comment]
@Ex-Communicad0 send the access details through mail
anilabhadatta@gmail.com

**Comment by Ex-Communicad0** [comment]
> @Ex-Communicad0 send the access details through mail [anilabhadatta@gmail.com](mailto:anilabhadatta@gmail.com)

Thanks, I have sent the details.

**Comment by anilabhadatta** [comment]
@Ex-Communicad0 should be fixed by now, check your email.

mandatory steps for linux vms
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.12
sudo apt install python3.12-venv
sudo apt install python3.12-tk
source env/bin/activate
python3.12 EducativeScraper.py

**Comment by Ex-Communicad0** [comment]
> @Ex-Communicad0 should be fixed by now, check your email.
> 
> mandatory steps for linux vms sudo add-apt-repository ppa:deadsnakes/ppa sudo apt install python3.12 sudo apt install python3.12-venv sudo apt install python3.12-tk source env/bin/activate python3.12 EducativeScraper.py

Thanks, There was a weird issue like it works with user not root level

after user permission i was getting permission error so I had to edit permission of the educative log file permission with write then it all worked

Wow, it's working so faster than my local Windows speed, can't thank you enough for this.

**Comment by anilabhadatta** [comment]
@Ex-Communicad0 yes linux is better in handling cpu/memory/disk intensive tasks.
Welcome
