### ISSUE TITLE
Group Downloaded Topics by "Modules" or "Sections"

### ISSUE THREAD

**Issue by sabz90** [anilabhadatta/educative.io_scraper#113]
First of all, thank you for creating this. I have a premium of educative and I use this tool so that I can access the material without internet (eg. travelling, staycation in remote areas, etc); this is very helpful!

**Is your feature request related to a problem? Please describe.**
All the topics are getting downloaded without being grouped under a "module". For example, here is the structure of a course in the website:
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/16514261/97e9d790-cb4b-496a-819e-0ad07e70a176)
The downloads are however like this -
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/16514261/54eee794-7d9e-42c2-8f5a-652c7fcd006b)

**Describe the solution you'd like**
All the topics must be grouped by their "module" folder.

**Describe alternatives you've considered**
Manual but it's a pain

**Comment by anilabhadatta** [comment]
@sabz90 use edu-viewer or maybe a write simple script, you can use the __toc__json  for reference.
But the solution you are asking cannot be implemented as it will break the current and older viewer.
