### ISSUE TITLE
Found Issue, Going Next Course Message: javascript error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by haha2345** [anilabhadatta/educative.io_scraper#12]
I meet  "_Found Issue, Going Next Course Message: javascript error: Maximum call stack size exceeded_"  when scrape the 22th course in https://www.educative.io/courses/grokking-the-machine-learning-interview/JEOBmok417l. 
The problem occurs after "Get HTML Page Content Using Single File Function".
Is this problem caused by my network or something else?

The log message as follows:
22 https://www.educative.io/courses/grokking-the-machine-learning-interview/R1VOnXE904L 
Message: javascript error: Maximum call stack size exceeded
  (Session info: headless chrome=96.0.4664.110)
Stacktrace:
Backtrace:
	Ordinal0 [0x00D06903+2517251]
	Ordinal0 [0x00C9F8E1+2095329]
	Ordinal0 [0x00BA2848+1058888]
	Ordinal0 [0x00BA4F44+1068868]
	Ordinal0 [0x00BA4E0E+1068558]
	Ordinal0 [0x00BA56BA+1070778]
	Ordinal0 [0x00BF64F9+1402105]
	Ordinal0 [0x00BE64D3+1336531]
	Ordinal0 [0x00BF5BBF+1399743]
	Ordinal0 [0x00BE639B+1336219]
	Ordinal0 [0x00BC27A7+1189799]
	Ordinal0 [0x00BC3609+1193481]
	GetHandleVerifier [0x00E95904+1577972]
	GetHandleVerifier [0x00F40B97+2279047]
	GetHandleVerifier [0x00D96D09+534521]
	GetHandleVerifier [0x00D95DB9+530601]
	Ordinal0 [0x00CA4FF9+2117625]
	Ordinal0 [0x00CA98A8+2136232]
	Ordinal0 [0x00CA99E2+2136546]
	Ordinal0 [0x00CB3541+2176321]
	BaseThreadInitThunk [0x761E6739+25]
	RtlGetFullPathName_UEx [0x77E48FEF+1215]
	RtlGetFullPathName_UEx [0x77E48FBD+1165]

**Comment by anilabhadatta** [comment]
@haha2345 maybe slow internet or the chrome was overloaded. restarting the scraper should fix the overloading issues but 
 not network issues.
the scraper works fine in my end, if it is not updated to v5.5 then please download the latest release
