### ISSUE TITLE
Chrome auto-update itself?

### ISSUE THREAD

**Issue by deniz946** [anilabhadatta/educative.io_scraper#14]
**Describe the bug**
After one scrape attempt, the next time I try to run the scrapper it fails due to version incompatibility with Chrome? I'm not sure if this is more an issue with the script itself or somehow Chrome auto-updates itself after its first usage or something like that?

I'm getting this error 
`Found Issue, Going Next Course Message: session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 103.0.5060.134 with binary path /Users/deniz946/Documents/Projects/educative.io_scraper/Chrome-bin/mac/Chromium.app/Contents/MacOS/Google Chrome`

**To Reproduce**
1. Run the script to scrape something, it works fine
2. Try starting another scrapping process later on
3. See error
`Found Issue, Going Next Course Message: session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 103.0.5060.134 with binary path /Users/deniz946/Documents/Projects/educative.io_scraper/Chrome-bin/mac/Chromium.app/Contents/MacOS/Google Chrome`

**Expected behavior**
Start scrapping the course listed in the urls file

**Screenshots**
<img width="940" alt="Captura de pantalla 2022-07-24 a las 21 07 31" src="https://user-images.githubusercontent.com/10478058/180662198-6c12be3d-da3f-4a79-9682-2d5db068d021.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 12.1 Monterey

**Comment by anilabhadatta** [comment]
@deniz946 in my macos, it didn't auto-update till now.
I will see if there is a way to disable auto-update Google chrome in MAC.

**Comment by anilabhadatta** [comment]
@deniz946 You can also update the chrome driver to the latest version as of now, I don't think it will cause any issues.

**Comment by anilabhadatta** [comment]
@deniz946 you could use the releases as of now, it won't auto-update itself and even if it does, restarting the scraper will use the old version always.

**Comment by anilabhadatta** [comment]
@deniz946 The best method i could find is blocking the update urls in hosts.
open the hosts using this command:  sudo nano /private/etc/hosts 
Paste the following URLs at the bottom.
google.com/dl/*
google.com/*
com/dl/*
*.gvt1.com
google.com/service/update2
google.com
googleapis.com/service/update2
google.com

Press Ctrl+O and then press Enter to overwrite the hosts file.
Press Ctrl+C to exit nano.

![image](https://user-images.githubusercontent.com/48487849/180666036-8e0a26e6-f03b-49e7-bb72-7af15ae11740.png)

This will block the update URL of Google Chrome in your system.

If you refer to the image below, you can see the present URL that is used by Google to AutoUpdate Chrome, so in future if the URL is changed then you will have to provide the new URL in your hosts file.
You can get the current update URL from the Info.plist file inside : /Users/anilabhadatta/Desktop/educative.io_scraper/Chrome-bin/mac/Chromium.app/Contents
Do not edit the Info.plist file as it will break the signature and you will not be able to open the app.
![image](https://user-images.githubusercontent.com/48487849/180666087-aac9c858-57dc-44bb-9245-070e64885e62.png)

**Comment by anilabhadatta** [comment]
@deniz946 Did the above steps fix your issue?
