### ISSUE TITLE
local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by zerohope** [anilabhadatta/educative.io_scraper#17]
when I press 4 after login Educative
![image](https://user-images.githubusercontent.com/19867950/194505862-5169521a-1ad4-4790-922d-53b5aea09566.png)
I also can't find the log file

**Comment by zerohope** [comment]
@anilabhadatta 
1) press 1 to generate the config
2) press 2 to select the config
![image](https://user-images.githubusercontent.com/19867950/194582667-fdbef653-75cb-4422-af34-92132dbcb9fe.png)
3) press 3 to login and press Enter after login
4) press 4

**Comment by anilabhadatta** [comment]
@zerohope remove everything and refer the soln posted here.
https://github.com/anilabhadatta/educative.io_scraper/issues/15

**Comment by anilabhadatta** [comment]
I think you made a mistake in urls.txt file or maybe the file path of urls.txt file.

**Comment by zerohope** [comment]
@anilabhadatta thank you so much, I can use it successfully.
The script can't copy code from the tab 
![image](https://user-images.githubusercontent.com/19867950/194678122-70457a43-2774-4c07-881c-d7bca00905d3.png)
(cplusplus programming for experienced engineers   19-number class definition with separate files)
as well as
![image](https://user-images.githubusercontent.com/19867950/194678139-1ec7f251-a2dc-43df-addb-7abcdc53f040.png)
(cplusplus programming for experienced engineers   22-number class in a dynamically linked library)
But it works wonderful in other pages

**Comment by anilabhadatta** [comment]
@zerohope can you send me the link of those topics. I will look into the issue.

**Comment by zerohope** [comment]
@anilabhadatta 
https://www.educative.io/courses/cpp-programming-experienced-devs/7nX8gA0WgrG
https://www.educative.io/courses/cpp-programming-experienced-devs/YMrV9WmpL3A

**Comment by anilabhadatta** [comment]
@zerohope I will look into this issue, if you face any more bugs while scraping please let me know.
