### ISSUE TITLE
Found Issue, Going Next Course too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by haha2345** [anilabhadatta/educative.io_scraper#23]
hello！ There are some problems when I used the version6.6 to scrape https://www.educative.io/module/lesson/dynamic-programming-cpp/qV7yoAqYgPG. 
The log shows '3 https://www.educative.io/module/lesson/dynamic-programming-cpp/qV7yoAqYgPG 
too many values to unpack (expected 2)' 
Please help!

**Comment by anilabhadatta** [comment]
@haha2345 checking

**Comment by anilabhadatta** [comment]
@haha2345 fixed
