### ISSUE TITLE
Found Issue, Going Next Course Message: no such element: Unable to locate element: {"method":"css selector","selector":"h4"}

### ISSUE THREAD

**Issue by EngAhmedSalah** [anilabhadatta/educative.io_scraper#25]
**Describe the bug**
I have this issue while trying to download a course
**Found Issue, Going Next Course Message: no such element: Unable to locate element: {"method":"css selector","selector":"h4"}**

**Expected behavior**
course downloaded successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/39335000/207356762-678f85e8-8c15-46eb-b238-0c3795e57e09.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]

**Comment by anilabhadatta** [comment]
Please provide the url of the topic @EngAhmedSalah

**Comment by EngAhmedSalah** [comment]
https://github.com/topics/educative-scraper

**Comment by anilabhadatta** [comment]
@EngAhmedSalah this is not i meant.
Which topic url of educative.io are you trying to scrap?

**Comment by skd1993** [comment]
@anilabhadatta i'm facing same issue
Course: https://www.educative.io/path/become-a-rust-professional
URL of first topic: https://www.educative.io/module/page/j2l3BzfAqpARx54pm/10370001/5387205784895488/5808916544094208
Does scraper not work on "modules" and "paths"?

**Comment by EngAhmedSalah** [comment]
> @EngAhmedSalah this is not i meant. Which topic url of educative.io are you trying to scrap?

this topic : https://www.educative.io/courses/grokking-dynamic-programming-patterns-for-coding-interviews/m2G1pAq0OO0

**Comment by anilabhadatta** [comment]
@EngAhmedSalah @skd1993 i will look into this issue

**Comment by anilabhadatta** [comment]
@skd1993 @EngAhmedSalah I think you are using the releases executables.
Please clone the repository using git and run the script manually -> steps are written on readme.
This is required since the executable releases are not up to date.

**Comment by skd1993** [comment]
> @skd1993 @EngAhmedSalah I think you are using the releases executables. Please clone the repository using git and run the script manually -> steps are written on readme. This is required since the executable releases are not up to date.

Thanks this is working for me now.

**Comment by EngAhmedSalah** [comment]
Hi @anilabhadatta  .
I tried to clone the project on an ubuntu machine and I get this error too.
![image](https://user-images.githubusercontent.com/39335000/208057669-70ef8d3f-659c-46f1-be9d-9de474033368.png)

**Comment by anilabhadatta** [comment]
Can you tell me your python version?

**Comment by EngAhmedSalah** [comment]
finally, the problem has been solved. the executable files are not up to date so. you should clone the repo manually and use it.
for Linux machines, use python 3.7 as @anilabhadatta mentioned.
thanks four your support.
