### ISSUE TITLE
hi @anilabhadatta  after adding the above driver able to login but the scrapper fails on the first page:

### ISSUE THREAD

**Issue by sarveshkhanna** [anilabhadatta/educative.io_scraper#28]
hi @anilabhadatta  after adding the above driver able to login but the scrapper fails on the first page:
0 https://www.educative.io/courses/grokking-adv-system-design-intvw/YQ49jQx9Ry2 
list index out of range
any way out

_Originally posted by @sarveshkhanna in https://github.com/anilabhadatta/educative.io_scraper/discussions/27#discussioncomment-4636056_

**Comment by sarveshkhanna** [comment]
![Screenshot 2023-01-09 at 10 56 08 PM](https://user-images.githubusercontent.com/9054658/211369815-a3966ed8-7a61-41a1-a9f4-85816df1d53c.png)
just created a folder structure but didn't proceed after that

**Comment by anilabhadatta** [comment]
@sarveshkhanna Please check the discussion for new replies.
