### ISSUE TITLE
Handle Quiz just like Slides

### ISSUE THREAD

**Issue by dev-rish** [anilabhadatta/educative.io_scraper#29]
Until now most of the things seem to work except Quiz page.
![image](https://user-images.githubusercontent.com/43387349/216751899-7aa26435-a30c-4bdc-89d1-d17924e5e30e.png)
Can you please extract all the quiz questions just like the slides are extracted.

**Comment by anilabhadatta** [comment]
@dev-rish please send the topic link, i have already implemented a code for a type of quiz container. I will try to implement this in free time.

**Comment by dev-rish** [comment]
@anilabhadatta You could use this as one of the examples https://www.educative.io/module/lesson/python-fundamentals-for-programmers/3jN0nW8r2ox

**Comment by anilabhadatta** [comment]
@dev-rish this is already implemented, please send the link of the topic present in your above image.

**Comment by anilabhadatta** [comment]
@dev-rish clone latest repo, added support for the quiz container.
check these links:
https://www.educative.io/courses/dynamic-programming-in-python/B1rnVm3AVno
https://www.educative.io/courses/grokking-the-principles-and-practices-of-advanced-system-design/JQxM3z8XyPo
https://www.educative.io/courses/launching-personal-website-r/m2jn9oYrP90

**Comment by dev-rish** [comment]
@anilabhadatta I have also noticed a bug. Try https://www.educative.io/module/lesson/python-fundamentals-for-programmers/Y5wJrN9Pn2K.

https://github.com/anilabhadatta/educative.io_scraper/blob/ad633b1b4415e07abb9e905bc3c4903ae35f6aff/educative_scraper.py#L114

There are cases when `name` is not in `meta_content` and hence it causes crash.

**Comment by anilabhadatta** [comment]
@dev-rish fixed, clone v7.0

**Comment by dev-rish** [comment]
@anilabhadatta Just curious, is there a reason for having relatively complex methods for getting file name ?
Until the last fix i have been using something like this and its been working fine
```
def get_file_name(driver, course_folder=False):
    print("Getting File Name")
    title = driver.title.split(' - ')

    if course_folder:
        file_name = title[-1]
    else:
        title.pop()
        file_name = "".join(title)

    file_name = slugify(file_name, replacements=[ ['+', 'plus'] ]).replace("-", " ")
    return re.sub(r'[:?|></]', replace_filename, file_name)
```

**Comment by anilabhadatta** [comment]
@dev-rish yes there is a need because few topics have a title with "-" so splitting will cause wrong file/course names.

**Comment by dev-rish** [comment]
@anilabhadatta Thanks for the speedy improvements & fixes
