### ISSUE TITLE
no such element: Unable to locate element: {"method":"css selector","selector":"nav[class*='ed-grid-sidebar']"}   (Session info: headless chrome=98.0.4758.102)

### ISSUE THREAD

**Issue by keiji11** [anilabhadatta/educative.io_scraper#3]
![unable_to_locate_element:{CSS}](https://user-images.githubusercontent.com/43145711/165790381-54763f37-4eb9-4845-8e9e-7056c2cd67e7.png)

**Comment by keiji11** [comment]
Ok, I bypassed the problem copying the link of a next lesson (the second instead the first).

**Comment by anilabhadatta** [comment]
@keiji11 always retry if there is any error while scraping, I have provided log.txt as well so that you can resume the scraping if there is any issue caused.
ed-grid-sidebar refers to the left side navbar and maybe due to slow internet the navbar didn't load so the scraper stopped.

**Comment by keiji11** [comment]
Ok, I bypassed the problem copying the link of a next lesson (the second instead the first).

But you're right, That's slow internet. Thanks
