### ISSUE TITLE
Message: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by sumant4ssm** [anilabhadatta/educative.io_scraper#30]
I am trying to download the below course 

https://www.educative.io/courses/grokking-coding-interview-patterns-java/g2wXzBm72L6

but always get this error just after starting the download

![image](https://user-images.githubusercontent.com/25642677/217045402-faf82737-50e4-4e5b-89cf-80360c7ac3c5.png)

**Comment by sumant4ssm** [comment]
Did a fresh setup but had no success, it downloads some of the course fine but it breaks with some too.

**Comment by anilabhadatta** [comment]
working fine at my end, 
stale element issues may occur due to slow internet.

**Comment by sumant4ssm** [comment]
Hi Anilabha,

It downloads the first two chapter fine then it breaks. I am not sure what
is going wrong. My internet speed is 300mbps.

Thank you,
Sumant

**Comment by sumant4ssm** [comment]
How can i delete the config files?

**Comment by anilabhadatta** [comment]
@sumant4ssm
C:\Users\<username>\.educative
I tested and it is working fine
![image](https://user-images.githubusercontent.com/48487849/217090645-9d874bde-ddc2-4b89-bd9c-d2d085024d89.png)
please send error data.

**Comment by sumant4ssm** [comment]
I am not able to figure out what is going wrong here -
https://user-images.githubusercontent.com/25642677/217092964-b271168e-e3bf-4824-840e-51954191d6ab.mp4

**Comment by sumant4ssm** [comment]
If you see the video above, do you notice any issue in console logs comparing with yours?

**Comment by anilabhadatta** [comment]
[2-two pointers introduction.zip](https://github.com/anilabhadatta/educative.io_scraper/files/10669402/2-two.pointers.introduction.zip)
slides are opening normally here.
@sumant4ssm 
Please clean install again and maybe try using headless = False mode

**Comment by anilabhadatta** [comment]
@sumant4ssm https://www.educative.io/courses/grokking-coding-interview-patterns-java/N75vOogKyl6
try scraping this in non headless mode and record a video showing the chrome tab.

**Comment by anilabhadatta** [comment]
@sumant4ssm clone again and test it now

**Comment by sumant4ssm** [comment]
thank you, let me try.

**Comment by anilabhadatta** [comment]
@sumant4ssm is it working now?

**Comment by sumant4ssm** [comment]
It's stuck on the third page. do you need video?

**Comment by anilabhadatta** [comment]
@sumant4ssm please send

**Comment by sumant4ssm** [comment]
It's still stuck on thirf page . here is the link - https://drive.google.com/file/d/1YwqHusEa7Jb-f9yZijLDBhDUMZH3GroK/view?usp=sharing

**Comment by anilabhadatta** [comment]
@sumant4ssm can you share remote control?

**Comment by sumant4ssm** [comment]
yeah sure, how should we do that?

**Comment by anilabhadatta** [comment]
send the creds to my mail anilabhadatta@gmail.com

**Comment by sumant4ssm** [comment]
337 790 482 - anydesk

**Comment by anilabhadatta** [comment]
@sumant4ssm i am sharing a zoom link
https://us05web.zoom.us/j/88105042666?pwd=dXpmMkU1ZzNzalhvT1Ric1FIV2ZCUT09

**Comment by anilabhadatta** [comment]
https://meet.google.com/ruk-zwcz-wtx
@sumant4ssm

**Comment by sumant4ssm** [comment]
Thanks, @anilabhadatta  for the help.

**Comment by anilabhadatta** [comment]
Welcome, closing this issue.
Issue Resolved: Python's latest version is required.
