### ISSUE TITLE
Unreadable text in some pages

### ISSUE THREAD

**Issue by Deviad** [anilabhadatta/educative.io_scraper#31]
Hello,
there seems to be an issue with the text in the courses. 
Some paragraphs have white text color. 
Is there anything that can be done?

**Comment by anilabhadatta** [comment]
@Deviad send the topic links and screenshot

**Comment by anilabhadatta** [comment]
@Deviad Try using dark mode in educative.io
![image](https://user-images.githubusercontent.com/48487849/218285871-6ffa3ef9-40fb-4e3f-9200-e284e54a279b.png)
