### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 98

### ISSUE THREAD

**Issue by Schachte** [anilabhadatta/educative.io_scraper#32]
I'm running into:

```
Found Issue, Going Next Course Message: session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 110.0.5481.100
```

I'm using the binary and driver from the most recent release. I'm running M1 ARM64 chip from Apple. Any tips?

**Comment by Schachte** [comment]
edit: Downloaded chrome drive from Google.
https://chromedriver.storage.googleapis.com/index.html?path=110.0.5481.77/

Working on M1 Mac ARM64. Cheers mate, thanks for maintaining this.

**Comment by anilabhadatta** [comment]
Can u create a pull request?
Also i would like to know if you have downloaded a different chrome binary or are you using the chrome binary for mac from releases?

**Comment by anilabhadatta** [comment]
@Schachte 
I have added a chromedriver v98 since the binary that i have provided is of v98.
Could you test by cloning the repo again and downloading the latest binary from releases?
