### ISSUE TITLE
Script is Increasing the VDI size in the BackGround while scrapping the files.

### ISSUE THREAD

**Issue by bibhubal** [anilabhadatta/educative.io_scraper#37]
**Describe the bug**
Hi @anilabhadatta  I am running this script in my virtualbox where guest OS is Ubuntu-22.04 host is windows11. The issue i am facing is while i am scrapping the files in the background its increasing the size of ubuntu VDI image with an alarming speed . It was initially 23Gb while in now i have downloaded around 500mb file my vdi size was increased to 35Gb in the middle and at last it is going beyind 40gb.
so exactly its increasing the footprint of VDI image nothing is happening in guest OS. looks like its impacting the base 
I have attached the screenshot.

![vdi-snapshot-start-time](https://user-images.githubusercontent.com/9507639/224469147-9bf311a1-2d0c-4bf1-80ab-f7b73e6c712f.png)

![vdi-snapshot-middle](https://user-images.githubusercontent.com/9507639/224469202-430977fa-75ee-46a6-81ba-d23f9d76e2b6.png)

Still Going

![image](https://user-images.githubusercontent.com/9507639/224471894-aca682f1-39ae-41f2-974d-5483fe67d70d.png)

**Comment by bibhubal** [comment]
@anilabhadatta Actual Downloaded file size is in the below snapshot.

![image](https://user-images.githubusercontent.com/9507639/224471964-b04e05e4-a5f8-469e-8800-d6c4924bf094.png)

**Comment by anilabhadatta** [comment]
@bibhubal, not any issue due to the scraper. VM images have a tendency to increase in size.
Apply fixed size when setting up vm.
