### ISSUE TITLE
No Python at 'C:\Users\anila\AppData\Local\Programs\Python\Python39\python.exe'

### ISSUE THREAD

**Issue by sachamorgese** [anilabhadatta/educative.io_scraper#4]
Hi, I've been trying to use your script a little on both Windows and MacOS but I've been unable to use it.
I've found several problems, using both the executables and the source code from this repo. I've been absolutely unable to use it.

On Windows I suspect you might have hardcoded Python in the executable. I get this when running it:

`No Python at 'C:\Users\anila\AppData\Local\Programs\Python\Python39\python.exe'`

**Comment by anilabhadatta** [comment]
@sachamorgese I didn't hardcoded python executable to my knowledge.
May I know which python file produced this error?

**Comment by umitkara** [comment]
@anilabhadatta same issue.  running the windows exe outputs this error message:
`No Python at 'C:\Users\anila\AppData\Local\Programs\Python\Python39\python.exe'
Traceback (most recent call last):
  File "multiprocess.py", line 96, in <module>
TypeError: an integer is required (got type NoneType)
[13052] Failed to execute script 'multiprocess' due to unhandled exception!`

**Comment by anilabhadatta** [comment]
@anilabhadatta i have already mentioned that multiprocess.py is not recommended to use.
Download the Manual Executable release or load chromedriver.py and educative_scraper.py in terminal (Also install the required dependencies).

**Comment by anilabhadatta** [comment]
>Create a virtual env and activate it
  pip3 install virtualenv 
  virtualenv env
 
>For windows:
  env\Scripts\activate
>For mac:
  source env/bin/activate

>Install required Modules
  pip3 install -r requirements.txt
  
>Run the following commands in separate terminals.
  python3 chromedriver.py
  python3 educative_scraper.py

**Comment by umitkara** [comment]
> @anilabhadatta i have already mentioned that multiprocess.py is not recommended to use. Download the Manual Executable release or load chromedriver.py and educative_scraper.py in terminal (Also install the required dependencies).

Thanks i tried the manual one and it worked. Thanks for reply.
