### ISSUE TITLE
On print command in chrome/edge the page gets blurred

### ISSUE THREAD

**Issue by sumant4ssm** [anilabhadatta/educative.io_scraper#41]
It happens with any course page. I am not sure if this is a bug with this scraper like drive issue or something else, but this is annoying and I can not take the printout of the page.

Steps to reproduce - 

1. Download any course
2. open the HTML page in chrome and try to print -> the preview page gets blurred-> even print pdf gets blurred

![image](https://user-images.githubusercontent.com/25642677/234365099-c193fec4-8720-4495-8e4b-f7655b9ad3cb.png)

Any help on this would be appreciated.

**Comment by sumant4ssm** [comment]
Yeah, I know but I feel It easy to take your own notes on a paper. Why does this not happen with firefox but only chromium based browser? the problem with firefox is CSS kind of gets messed up.

**Comment by anilabhadatta** [comment]
![image](https://user-images.githubusercontent.com/48487849/234494109-29850bda-eed9-4346-add3-5694cdf5bd0c.png)
@sumant4ssm You can try uncommenting line 1119 and comment lines 1120,1121,1122.
This will save the whole page as a screenshot. this should help you in printing the HTML page on your paper.
But be aware text may be cut in between.

**Comment by sumant4ssm** [comment]
Thanks, I'll check it out.

**Comment by sumant4ssm** [comment]
does it generate an html file or image file? I get only html file with same issue. I followed your instruction.

**Comment by anilabhadatta** [comment]
@sumant4ssm html with image file

**Comment by anilabhadatta** [comment]
@sumant4ssm In brave browser the pdf is loading properly while printing

**Comment by anilabhadatta** [comment]
Fixed, Scrape the contents again. Printing and mobile view will work properly now.

**Comment by sumant4ssm** [comment]
Great, Thank you!!
