### ISSUE TITLE
Not working any more

### ISSUE THREAD

**Issue by bibhubal** [anilabhadatta/educative.io_scraper#44]
**Describe the bug**

##############
                Scraper Started, Log file can be found in Save directory

    

Driver Loaded

                            [Selected config: 0] Starting Scraping: 0, https://www.educative.io/courses/decode-coding-interview-java/3woxv5GoKmQ

                

Load Webpage Function

Checking Login Function

Checking for captcha Function...

Create Course Folder Function

Getting File Name

> This is a module page

Get File name module

Inside Course Folder

Checking Login Function

Checking for captcha Function...

Scrolling Page

Getting File Name

> This is a module page

Get File name module

Checking page

Removing Nav tags from page

Node deleted div[class*='ed-grid'] > nav

Node deleted div[class*='ed-grid'] > nav

Show Hints Function

No hints found

Inside find_mark_down_quiz_containers function

No mark down quiz_container found

Show Codebox Answers Function

No Codebox answers found

Finding Slides Function

No Slides Found

Inside take_quiz_screenshot function

Quiz not found

Adding Name Tag in Next Back Button

Fixing SVG Tags inside Object Tags

Get HTML Page Content Using Single File Function

make_code_selectable function

make_code_selectable function executed

Creating HTML File

HTML File Created

HTML Page content taken.

Inside Widget Container Function

No widget container found

Code Container Download Type Function

No Code Container Downloadable Type found

Code Container Clipboard Type Function

No code containers found

Remove Mark completed

Next Page Function

Going Next Page

--------------- 0 Complete-------------------

Checking Login Function

Checking for captcha Function...

Scrolling Page

Getting File Name

> This is a module page

Get File name module

Checking page

Removing Nav tags from page

Node deleted div[class*='ed-grid'] > nav

Node deleted div[class*='ed-grid'] > nav

Show Hints Function

No hints found

Inside find_mark_down_quiz_containers function

No mark down quiz_container found

Show Codebox Answers Function

No Codebox answers found

Finding Slides Function

No Slides Found

Inside take_quiz_screenshot function

Quiz not found

Adding Name Tag in Next Back Button

Fixing SVG Tags inside Object Tags

Get HTML Page Content Using Single File Function

make_code_selectable function

make_code_selectable function executed

Creating HTML File

HTML File Created

HTML Page content taken.

Inside Widget Container Function

No widget container found

Code Container Download Type Function

No Code Container Downloadable Type found

Code Container Clipboard Type Function

No code containers found

Remove Mark completed

Next Page Function

Going Next Page

--------------- 1 Complete-------------------

Checking Login Function

Checking for captcha Function...

Scrolling Page

Getting File Name

> This is a module page

Get File name module

Checking page

Removing Nav tags from page

Node deleted div[class*='ed-grid'] > nav

Node deleted div[class*='ed-grid'] > nav

Show Hints Function

No hints found

Inside find_mark_down_quiz_containers function

No mark down quiz_container found

Show Codebox Answers Function

No Codebox answers found

Finding Slides Function

No Slides Found

Inside take_quiz_screenshot function

Quiz not found

Adding Name Tag in Next Back Button

Fixing SVG Tags inside Object Tags

Get HTML Page Content Using Single File Function

make_code_selectable function

make_code_selectable function executed

Creating HTML File

HTML File Created

HTML Page content taken.

Inside Widget Container Function

No widget container found

Code Container Download Type Function

No Code Container Downloadable Type found

Code Container Clipboard Type Function

No code containers found

Remove Mark completed

Next Page Function

Going Next Page

--------------- 2 Complete-------------------

Checking Login Function

Checking for captcha Function...

Scrolling Page

Getting File Name

> This is a module page

Get File name module

Checking page

Removing Nav tags from page

Node deleted div[class*='ed-grid'] > nav

Node deleted div[class*='ed-grid'] > nav

Show Hints Function

No hints found

Inside find_mark_down_quiz_containers function

No mark down quiz_container found

Show Codebox Answers Function

No Codebox answers found

Finding Slides Function

No Slides Found

Inside take_quiz_screenshot function

Quiz not found

Adding Name Tag in Next Back Button

Fixing SVG Tags inside Object Tags

Get HTML Page Content Using Single File Function

make_code_selectable function

make_code_selectable function executed

Creating HTML File

HTML File Created

HTML Page content taken.

Inside Widget Container Function

No widget container found

Code Container Download Type Function

No Code Container Downloadable Type found

Code Container Clipboard Type Function

No code containers found

Remove Mark completed

Next Page Function

Going Next Page

--------------- 3 Complete-------------------

Checking Login Function

Checking for captcha Function...

Scrolling Page

Getting File Name

> This is a module page

Get File name module

Checking page

Removing Nav tags from page

Node deleted div[class*='ed-grid'] > nav

Node deleted div[class*='ed-grid'] > nav

Show Hints Function

No hints found

Inside find_mark_down_quiz_containers function

No right button found in Mark Down Quiz

Clicking on Mark Down Quiz function

Found Issue, Going Next Course Message: no such element: Unable to locate element: {"method":"css selector","selector":"span"}

  (Session info: headless chrome=98.0.4758.102)

Stacktrace:

#0 0x559e6a0edb33 <unknown>

#1 0x559e69bb66d8 <unknown>

#2 0x559e69bec6f1 <unknown>

#3 0x559e69bec8b1 <unknown>

#4 0x559e69be1067 <unknown>

#5 0x559e69c0a08d <unknown>

#6 0x559e69be0fa3 <unknown>

#7 0x559e69c0a16e <unknown>

#8 0x559e69c1d2fb <unknown>

#9 0x559e69c09f53 <unknown>

#10 0x559e69bdfa0a <unknown>

#11 0x559e69be0ad5 <unknown>

#12 0x559e6a11f2fd <unknown>

#13 0x559e6a1384bb <unknown>

#14 0x559e6a1210d5 <unknown>

#15 0x559e6a139145 <unknown>

#16 0x559e6a114aaf <unknown>

#17 0x559e6a155ba8 <unknown>

#18 0x559e6a155d28 <unknown>

#19 0x559e6a17048d <unknown>

#20 0x7f3111490402 <unknown>

Script Execution Complete

                        Educative Scraper (version 7.2), developed by Anilabha Datta

######################################################################

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anilabhadatta** [comment]
@bibhubal before requesting an issue please do check if you are updated to the latest repo.
The current version is 8.5.
Stop using the releases since they are not updated.
Run the program manually, steps given in readme.

**Comment by bibhubal** [comment]
@anilabhadatta Thanks Just for heads up its bit slow although it solves the purpose. if you can make it Golang or Rust it will be better.

**Comment by bibhubal** [comment]
Closing
