### ISSUE TITLE
Scrapping is being stale at one page 

### ISSUE THREAD

**Issue by bibhubal** [anilabhadatta/educative.io_scraper#45]
**Describe the bug**
Hi Anil,

I am getting the issues where scrapping is being stale one point. Tried multiple times its giving some error.
Tried 3 to 4 times by reconfiguring ubuntu and MX Linux but at the same point its getting stopped..

https://www.educative.io/courses/grokking-dynamic-programming-a-deep-dive-using-python/7A3RLnnRvOy

![image](https://github.com/anilabhadatta/educative.io_scraper/assets/9507639/7bf99b19-004d-4b3c-880d-4afdfef3ff7d)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anilabhadatta** [comment]
@bibhubal This is a getting file name issue. Will look into this.

**Comment by anilabhadatta** [comment]
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/48487849/94fcb8b2-3dd8-4117-accc-dfd46a16acff)
Working at my end, try using headless=False or in another operating system.

**Comment by bibhubal** [comment]
Closing as the issue is fixed.
