### ISSUE TITLE
Found Issue, Going Next Course [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by EngAhmedSalah** [anilabhadatta/educative.io_scraper#47]
**Describe the bug**
while trying to download this page [Challenge 1: Implement the Rectangle Class Using the Concepts of Encapsulation](https://www.educative.io/module/lesson/object-oriented-programming/g7l7GnGGo6D)

**Expected behavior**
downloading successfully

**Screenshots**
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/39335000/c9973977-9bcf-4c1c-8925-22c2111f35d0)

**Comment by anilabhadatta** [comment]
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/48487849/b629e286-b9a5-4f38-8c56-97676c4f0c7c)

I have tested both single-file html and screenshot HTML. Both ran successfully. Check your internet or update to the repo's latest version; the minimum Python version of virtual env should match the requirements given in the Readme.

**Comment by anilabhadatta** [comment]
@EngAhmedSalah v3 released, reclone to a new folder and refer readme for setup instructions
