### ISSUE TITLE
no chrome binary 

### ISSUE THREAD

**Issue by wild20tea** [anilabhadatta/educative.io_scraper#49]
**Describe the bug**
Program can't file no chrome binary

**To Reproduce**
When I try to log in at step 3

**Screenshots**
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/122171550/679ae53b-553d-4449-bc87-f384b658a779)

**Desktop (please complete the following information):**
 - OS: Ubuntu, I also try on mint but still the same.

Thanks for your help

**Comment by anuragdev101** [comment]
I'm getting the same error, please help

**Comment by wild20tea** [comment]
a

**Comment by anilabhadatta** [comment]
@wild20tea Which arch ubuntu? Is it running on arm64 or amd64?
Download the chrome binary for that arch from releases

**Comment by anilabhadatta** [comment]
@wild20tea v3 released, reclone to a new folder and refer readme for setup instructions
