### ISSUE TITLE
code clipboard files can be enhanced with naming convention

### ISSUE THREAD

**Issue by anuragdev101** [anilabhadatta/educative.io_scraper#50]
**Is your feature request related to a problem? Please describe.**
Currently, the code clipboards being downloaded are anonymous by file name and aren't easily readable
Current code clipboard path: ./code_clipboard0/code-0.txt

**Describe the solution you'd like**
Single code clipboard file for all the code clipboards per course topic. Sample result file attached.

**Additional context**
For example: To scrape the code "kubectl run db --image mongo" from the below snippet,
![1](https://github.com/anilabhadatta/educative.io_scraper/assets/41896871/b1279cce-cbc4-4b42-a335-2811fc872558)
dentifiable.
 we can scrape the caption-text from the second attached image showing the span tag, and create a single file.
![2](https://github.com/anilabhadatta/educative.io_scraper/assets/41896871/99c14c3f-336a-49b0-a3b7-e71a908c748c)

Our final code_clipboard.txt file can be like this:

[code_clipboard.txt](https://github.com/anilabhadatta/educative.io_scraper/files/12185977/code_clipboard.txt)

**Comment by anilabhadatta** [comment]
@anuragdev101 There are various different type of containers in educative so for each container i have created code_container_index folder.
It will be confusing I guess to append.
It just needs a small automation and appending the files with proper file name to mark the container index.
I have some different plans before implementing this but I am not getting enough time and help.

**Comment by anilabhadatta** [comment]
@anuragdev101 v3 released, reclone to a new folder and refer readme for setup instructions
