### ISSUE TITLE
Crash on certain pages

### ISSUE THREAD

**Issue by dev-rish** [anilabhadatta/educative.io_scraper#51]
These are some of the page where the program crashes
https://www.educative.io/courses/grokking-the-behavioral-interview/YQXMlDkqpoA
https://www.educative.io/courses/recursion-for-coding-interviews-in-java/m2qwWvOjR0R

**Comment by anilabhadatta** [comment]
@dev-rish share crash info and also try using latest commit
https://github.com/anilabhadatta/educative.io_scraper/commit/f22caafdbca4abb2b7d5a55240eafa4ea379cc26

**Comment by anilabhadatta** [comment]
@dev-rish try using v3, issues should be resolved
