### ISSUE TITLE
downloading the same module many times

### ISSUE THREAD

**Issue by EngAhmedSalah** [anilabhadatta/educative.io_scraper#52]
**Describe the bug**
while trying to download this course https://www.educative.io/courses/grokking-modern-system-design-interview-for-engineers-managers
as you can see, it downloaded the same module many times

**Screenshots**
<img width="252" alt="Screenshot 2023-08-05 173234" src="https://github.com/anilabhadatta/educative.io_scraper/assets/39335000/b78328fa-62d6-4f54-b7ae-8d2c54648c68">

**Comment by anilabhadatta** [comment]
@EngAhmedSalah https://github.com/anilabhadatta/educative.io_scraper/commit/f22caafdbca4abb2b7d5a55240eafa4ea379cc26
fixed in latest commit

**Comment by anilabhadatta** [comment]
@EngAhmedSalah v3 released, reclone to a new folder and refer readme for setup instructions
