### ISSUE TITLE
Getting exception while trying to do login to educative (Option 3)

### ISSUE THREAD

**Issue by aayushagarwal** [anilabhadatta/educative.io_scraper#53]
**Describe the bug**
<img width="667" alt="image" src="https://github.com/anilabhadatta/educative.io_scraper/assets/6272943/d4da1c2e-dc3b-4c89-8d55-1efe8a3e0cc6">

**Laptop (please complete the following information):**
 - OS: Mac OS Ventura 13.4.1 (M2 chip)
 - Browser: Chrome 
 - Version: Version 115.0.5790.170 (Official Build) (arm64)

**Comment by anilabhadatta** [comment]
@aayushagarwal 
Tell me the complete steps how you started the script

**Comment by anilabhadatta** [comment]
chmod +x <exec> might fix

**Comment by anilabhadatta** [comment]
@aayushagarwal v3 released, reclone to a new folder and refer readme for setup instructions
