### ISSUE TITLE
 ERROR - StartScraper - start: 20: ExtensionScraper:start: 43: ExtensionScraper:scrapeCourse: 67: CourseCollectionsJson and CourseTopicUrlsList Urls are not equal

### ISSUE THREAD

**Issue by Dan733** [anilabhadatta/educative.io_scraper#61]
**Describe the bug**
Course scrape fails with the following error:

 ERROR - StartScraper - start: 20: ExtensionScraper:start: 43: ExtensionScraper:scrapeCourse: 67: CourseCollectionsJson and CourseTopicUrlsList Urls are not equal

**To Reproduce**
1. Add the following url for system design course: https://www.educative.io/courses/grokking-modern-system-design-interview-for-engineers-managers/introduction-to-modern-system-design
2. Start scraper

**Expected behavior**
Scraper should scrape course

**Desktop (please complete the following information):**
Running windows 10

**Comment by anilabhadatta** [comment]
@Dan733 will look into the issue, could you attach the log file?

**Comment by anilabhadatta** [comment]
@Dan733 pull latest commit and test

**Comment by Dan733** [comment]
Looks like it's working now, thank you!

**Comment by Dan733** [comment]
Actually, it fails about 15% of the way in with the following error:

2023-09-12 20:21:53,178 - ERROR - StartScraper - start: 20: ExtensionScraper:start: 43: ExtensionScraper:scrapeCourse: 81: ExtensionScraper:scrapeTopic: 96: SeleniumBasicUtility:waitWebdriverToLoadTopicPage: 48: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF730FD7862+54818]
	(No symbol) [0x00007FF730F46A92]
	(No symbol) [0x00007FF730DFDA3B]
	(No symbol) [0x00007FF730E3E4FC]
	(No symbol) [0x00007FF730E3E67C]
	(No symbol) [0x00007FF730E79627]
	(No symbol) [0x00007FF730E5EAEF]
	(No symbol) [0x00007FF730E775A2]
	(No symbol) [0x00007FF730E5E883]
	(No symbol) [0x00007FF730E33691]
	(No symbol) [0x00007FF730E348D4]
	GetHandleVerifier [0x00007FF73133B962+3610402]
	GetHandleVerifier [0x00007FF731391830+3962352]
	GetHandleVerifier [0x00007FF731389D1F+3930847]
	GetHandleVerifier [0x00007FF731073616+693206]
	(No symbol) [0x00007FF730F515F8]
	(No symbol) [0x00007FF730F4D904]
	(No symbol) [0x00007FF730F4DA32]
	(No symbol) [0x00007FF730F3E0E3]
	BaseThreadInitThunk [0x00007FFFDCFB7614+20]
	RtlUserThreadStart [0x00007FFFDDA426B1+33]

 2023-09-12 20:21:53,179 - DEBUG - StartScraper - Exiting Scraper...

**Comment by anilabhadatta** [comment]
@Dan733 attach log file

**Comment by Dan733** [comment]
[EducativeScraper.log](https://github.com/anilabhadatta/educative.io_scraper/files/12600352/EducativeScraper.log)

**Comment by anilabhadatta** [comment]
@Dan733 clone latest version, should work

**Comment by Dan733** [comment]
I can confirm it works, thank you.
