### ISSUE TITLE
unable to proceed due to captcha

### ISSUE THREAD

**Issue by bluebob297** [anilabhadatta/educative.io_scraper#73]
After pressing 'start scraper' and entering login credentials, a cloudflare captcha is displayed and stuck in an infinite loop.

**Comment by anilabhadatta** [comment]
@bluebob297 which chrome version are you using?

**Comment by anhpho** [comment]
@bluebob297 this happened because you're scraping too much. It would help if you let the app retire and return after a period. Or you can try to scrape through using a proxy that changes your IP to bypass Cloudflare.

**Comment by bluebob297** [comment]
Thanks for the info
