### ISSUE TITLE
Can't get full source code files

### ISSUE THREAD

**Issue by anhpho** [anilabhadatta/educative.io_scraper#75]
There is no errors but the scraper can't get full source code files.
Example: https://www.educative.io/module/page/P1vxGOto4z83LN78X/10370001/6275949640548352/4625710514438144

Expected: Can get full source code files.
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/11723588/340b8a7e-402c-4737-a958-7e8f267bd214)
Actually: only one file app.py can got.
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/11723588/f2b8da1f-1181-4224-9d24-240e5207e742)

**Comment by anilabhadatta** [comment]
@anhpho will look. this should be fixed in my previous commit.

**Comment by anhpho** [comment]
I found the root cause. This code below only get the first file at the level 1 source code folder or all files below if this one is a folder. All others files or folder at level 1 will be skipped. I think a loop should be there. Anyway would you mind if I fix it tomorrow. Now is too late at my place.
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/11723588/7e6f52f9-4ab6-4ade-bcd6-6fcd0f2aa024)

**Comment by anilabhadatta** [comment]
@anhpho you are right maybe, a loop should have been there,just see if you can fix it. I am not getting enough time to look into the issues. If you need help i will help you.

**Comment by anilabhadatta** [comment]
@anhpho recently committed, test it for other links as well having similar code window

**Comment by anhpho** [comment]
@anilabhadatta confirm it has already fixed.

**Comment by anilabhadatta** [comment]
@anhpho i need to add one feature.
Scrape the first topic url from every course.
There is an api
api/reader/featured_items

But this only produces the course list
The Toc is not present here.
The only solution i can think is traversing all the course urls and then getting the first link.

**Comment by anhpho** [comment]
@anilabhadatta agree with that. It may be the easiest way that we have right now.

**Comment by anilabhadatta** [comment]
@anhpho no of requests will be 700+ at least but i can't find any other api that can provide the toc 
Or i can change a slight logic but i am not sure if it will work or not.
Open the course link, if it is a topic link then continue as usual but if it is a course link then start scraping from first url 
Will see if this can be added in logic

**Comment by anilabhadatta** [comment]
@anhpho this is fixed, also all course topic urls generator was added as well., closing this issue
