### ISSUE TITLE
Error: ShowUtility:showCodeSolutions: 59: Message: javascript error: Cannot read properties of null (reading 'click')

### ISSUE THREAD

**Issue by anhpho** [anilabhadatta/educative.io_scraper#79]
**Description:** Show code solutions without the confirm button cause this error.
**Error link:** [link](https://www.educative.io/module/page/mwo3kDtPGv91GNR8v/10370001/4786389594144768/5972458113073152)
**Logs:**
ERROR - StartScraper - start: 20: CourseTopicScraper:start: 53: CourseTopicScraper:scrapeCourse: 100: CourseTopicScraperMain:scrapeTopic: 126: ShowUtility:showCodeSolutions: 59: Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome=116.0.5845.96)
Stacktrace:
        GetHandleVerifier [0x00007FF710ED52A2+57122]
        (No symbol) [0x00007FF710E4EA92]
        (No symbol) [0x00007FF710D1E3AB]
        (No symbol) [0x00007FF710D22382]
        (No symbol) [0x00007FF710D24063]
        (No symbol) [0x00007FF710D8F214]
        (No symbol) [0x00007FF710D76FDA]
        (No symbol) [0x00007FF710D8EB82]
        (No symbol) [0x00007FF710D76DB3]
        (No symbol) [0x00007FF710D4D2B1]
        (No symbol) [0x00007FF710D4E494]
        
**Issue fix suggests:** Add optional chaining operator before clicking the confirm button.
![image](https://github.com/anilabhadatta/educative.io_scraper/assets/11723588/7f054b86-f74a-44c2-883b-126962089f43)

**Comment by anilabhadatta** [comment]
@anhpho your solutions looks correct, can you create a PR for this?

**Comment by anhpho** [comment]
> @anhpho your solutions looks correct, can you create a PR for this?

here PR #80

**Comment by anilabhadatta** [comment]
@anhpho there was a bug here as well, i have fixed it in latest commits.
The button was showing after a delay so added a delay in js.
There were multiple bug/reliability fixes, this may show that the scraper is slow in performance but reliability has increased in scraping topics.
