### ISSUE TITLE
request-html would might be a good and fast alternative for selenium

### ISSUE THREAD

**Issue by abhinavm24** [anilabhadatta/educative.io_scraper#84]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anilabhadatta** [comment]
@abhinavm24 not possible at the moment, reason: 
1. session is stored locally using chrome user-data-dir, manages login system and stays logged in forever if the account is not authenticated in another device.
2. the browser also helps in calling the api's that are auth protected so only logged in user can request and get an response
3. single-file is integrated and it is well designed to scrape HTML data without any data loss and also removes js code, also the images are saved in base64 format so they are not linked to educative's servers.
4. request-html also does the same thing by loading a browser and generating a response but doesn't help in obtaining the first 2 objectives that are mandatory
5. also request-html is only created for python3.6, and not sure if the response if generated as good as singlefile.

**Comment by anilabhadatta** [comment]
@abhinavm24 major updates were pushed, do check out.
Ucdriver is integrated now

**Comment by abhinavm24** [comment]
great work @anilabhadatta, will get scrapping then
